package api

import "github.com/hkjang/relio/internal/platform/version"

func OpenAPI() map[string]any {
	return map[string]any{
		"openapi": "3.1.0",
		"info":    map[string]any{"title": "Relio REST API", "version": version.Current().Version, "description": "오프라인 B2B CRM 및 영업관리 API. 세션 또는 Personal Access Key로 인증합니다."},
		"servers": []map[string]any{{"url": "/api/v1"}},
		"components": map[string]any{
			"securitySchemes": map[string]any{"personalKey": map[string]any{"type": "http", "scheme": "bearer", "description": "relio_{keyId}_{secret}"}},
			"schemas":         map[string]any{"Error": map[string]any{"type": "object", "properties": map[string]any{"error": map[string]any{"type": "object", "properties": map[string]any{"code": map[string]any{"type": "string"}, "message": map[string]any{"type": "string"}, "requestId": map[string]any{"type": "string"}}}}}},
		},
		"security": []map[string]any{{"personalKey": []string{}}},
		"paths": map[string]any{
			"/system/version":               get("서비스 빌드 버전", false),
			"/customers":                    methods("고객 검색 및 생성", "customer:read", "customer:write"),
			"/customers/{id}":               readUpdateDelete("고객 조회, 수정 및 삭제", "customer:read", "customer:write", "customer:delete"),
			"/customers/{id}/360":           get("Customer 360", "customer:read + opportunity:read + activity:read"),
			"/customers/{id}/relationships": methods("고객 담당자 Relationship Graph", "customer:read + contact:read", "contact:write"),
			"/customers/{id}/relationships/{relationshipId}": map[string]any{"put": operation("담당자 관계 수정", "contact:write"), "delete": operation("담당자 관계 삭제", "contact:write")},
			"/customers/{id}/account-plan":                   readUpdate("Strategic Account Plan", "customer:read", "customer:write"),
			"/customers/{id}/cross-sell":                     get("White Space Cross-sell 후보", "customer:read"),
			"/customers/{id}/duplicates":                     get("중복 고객 후보", "customer:read"),
			"/customers/{id}/merge":                          map[string]any{"post": operation("고객 병합", "customer:write")},
			"/contacts":                                      methods("담당자 조회 및 생성", "contact:read", "contact:write"),
			"/signals":                                       get("Signal 조회", "intelligence:read"),
			"/signals/{id}":                                  get("Signal 상세", "intelligence:read"),
			"/signals/{id}/ignore":                           map[string]any{"post": operation("Signal 무시", "intelligence:write")},
			"/risks":                                         get("Risk 조회", "intelligence:read"),
			"/risks/{id}":                                    get("Risk 상세", "intelligence:read"),
			"/risks/{id}/explain":                            get("Risk 점수 근거 설명", "intelligence:read"),
			"/risks/{id}/accept":                             map[string]any{"post": operation("Risk 감수 처리", "intelligence:write")},
			"/insights":                                      get("Insight 조회", "intelligence:read"),
			"/insights/{id}":                                 get("Insight 상세", "intelligence:read"),
			"/recommendations":                               get("추천 행동 조회", "intelligence:read"),
			"/recommendations/{id}":                          get("추천 행동 상세", "intelligence:read"),
			"/recommendations/{id}/accept":                   map[string]any{"post": operation("추천 수락 및 Task 생성", "intelligence:write")},
			"/recommendations/{id}/dismiss":                  map[string]any{"post": operation("추천 무시", "intelligence:write")},
			"/customers/{id}/intelligence":                   get("고객 Intelligence 패널", "intelligence:read"),
			"/intelligence/status":                           get("마지막 분석 실행 결과", "intelligence:read"),
			"/intelligence/run":                              map[string]any{"post": operation("Intelligence 분석 즉시 실행", "intelligence:run")},
			"/contacts/{id}":                                 map[string]any{"put": operation("담당자 수정", "contact:write"), "delete": operation("담당자 삭제", "contact:write")},
			"/leads":                                         methods("Lead 조회 및 생성", "lead:read", "lead:write"),
			"/opportunities":                                 methods("영업기회 조회 및 생성", "opportunity:read", "opportunity:write"),
			"/opportunities/{id}":                            readUpdate("영업기회 조회 및 수정", "opportunity:read", "opportunity:write"),
			"/opportunities/{id}/stage":                      map[string]any{"post": operation("Stage 변경", "opportunity:write")},
			"/opportunities/{id}/health":                     get("설명 가능한 Deal Health", "opportunity:read"),
			"/opportunities/{id}/inspection":                 get("Deal 변화 및 위험 분석", "opportunity:read"),
			"/opportunities/{id}/playbook":                   readUpdate("Stage Sales Playbook", "opportunity:read", "opportunity:write"),
			"/opportunities/{id}/stage-readiness":            get("Stage Exit Criteria 판정", "opportunity:read"),
			"/opportunities/{id}/team":                       get("Opportunity Team", "opportunity:read"),
			"/opportunities/{id}/team/{userId}":              map[string]any{"put": operation("Opportunity Team 구성원 저장", "opportunity:write"), "delete": operation("Opportunity Team 구성원 제외", "opportunity:write")},
			"/collaborators":                                 get("Data Scope 내 협업 사용자", "opportunity:read"),
			"/deal-intelligence/at-risk":                     get("위험 Deal 우선순위", "opportunity:read"),
			"/deal-intelligence/coaching":                    get("팀장 Sales Coaching", "opportunity:read"),
			"/activities":                                    methods("활동 조회 및 등록", "activity:read", "activity:write"),
			"/pipeline":                                      get("Pipeline 조회", "opportunity:read"),
			"/products":                                      methods("상품 조회 및 생성", "product:read", "product:write"),
			"/products/{id}":                                 map[string]any{"put": operation("상품 수정", "product:write"), "delete": operation("상품 삭제 또는 판매중지", "product:write")},
			"/forecasts":                                     get("Forecast 조회", "forecast:read"),
			"/forecasts/intelligence":                        get("Forecast Snapshot 및 Waterfall", "forecast:read"),
			"/forecasts/overrides/{id}":                      map[string]any{"put": operation("Manager Forecast Override", "forecast:write")},
			"/sales/kpi":                                     get("영업 KPI", "sales:read"),
			"/tasks/due":                                     get("기한 임박 후속 활동", "activity:read"),
			"/quotations":                                    methods("견적 조회 및 생성", "quotation:read", "quotation:write"),
			"/contracts":                                     methods("계약 조회 및 생성", "contract:read", "contract:write"),
			"/contracts/{id}":                                get("다중 통화 계약 상세", "contract:read"),
			"/contracts/{id}/activate":                       map[string]any{"post": operation("계약 활성화 및 매출 일정 자동 생성", "contract:write")},
			"/contracts/{id}/revenue-schedule":               get("계약 매출 인식 일정", "contract:read"),
			"/contracts/{id}/renewal":                        map[string]any{"put": operation("계약 갱신 진행상태 및 다음 행동 저장", "contract:write")},
			"/revenue-schedules/{id}/recognize":              map[string]any{"post": operation("예정 매출 인식 및 Sales Ledger 반영", "sales:write")},
			"/sales":                                         methods("매출 조회 및 등록", "sales:read", "sales:write"),
			"/targets":                                       methods("영업목표 조회 및 생성", "target:read", "target:write"),
			"/notifications":                                 get("알림 조회", "notification:read"),
			"/notifications/{id}/read":                       map[string]any{"post": operation("알림 읽음 처리", "notification:write")},
			"/reports":                                       get("영업 보고서", "report:read"),
			"/today":                                         get("오늘 먼저 할 일 우선순위 큐", "opportunity:read"),
			"/customers/{id}/risk":                           get("고객 이탈 위험도와 근거", "voice:read"),
			"/voices":                                        methods("고객의 목소리 조회 및 접수", "voice:read", "voice:write"),
			"/voices/{id}":                                   readUpdate("고객 요청 상세 및 처리", "voice:read", "voice:write"),
			"/voices/{id}/events":                            map[string]any{"post": operation("처리 기록·고객 응대 추가", "voice:write")},
			"/voices/summary":                                get("고객의 목소리 요약 지표", "voice:read"),
			"/voices/categories":                             get("고객 요청 유형 및 SLA 목표", "voice:read"),
			"/voices/export":                                 get("고객의 목소리 CSV 내보내기", "voice:read"),
			"/admin/voice-categories":                        methods("요청 유형 조회 및 생성", "admin:read", "admin:write"),
			"/admin/analytics":                               methods("방문자 분석 공급자 조회 및 추가", "analytics:manage", "analytics:manage"),
			"/admin/analytics/{id}":                          map[string]any{"put": operation("방문자 분석 공급자 변경", "analytics:manage"), "delete": operation("방문자 분석 공급자 삭제", "analytics:manage")},
			"/admin/analytics/violations/resolve":            map[string]any{"post": operation("차단 보고 무시 처리", "analytics:manage")},
			"/csp-report":                                    map[string]any{"post": operation("브라우저 CSP 위반 보고 수집", "")},
			"/admin/voice-categories/{id}":                   map[string]any{"put": operation("요청 유형·SLA 변경", "admin:write"), "delete": operation("요청 유형 삭제 또는 사용중지", "admin:write")},
			"/reports/win-loss":                              get("Win/Loss 분석", "report:read"),
			"/search":                                        get("Data Scope 적용 통합 검색", "customer:read"),
			"/approvals":                                     methods("승인 요청 목록 및 제출", "approval:request", "approval:request"),
			"/approvals/status":                              get("승인 Workflow 활성 상태", "approval:request"),
			"/approvals/capability":                          get("대상별 승인 정책 판정", "approval:request"),
			"/approvals/{id}":                                get("승인 상태", "approval:request"),
			"/approvals/{id}/approve":                        map[string]any{"post": operation("승인", "approval:approve")},
			"/approvals/{id}/reject":                         map[string]any{"post": operation("반려", "approval:approve")},
			"/me/keys":                                       methods("개인 API/MCP Key 목록 및 생성", "", ""),
			"/me/keys/{id}/rotate":                           map[string]any{"post": operation("개인 Key Rotation", "")},
			"/me/keys/{id}":                                  map[string]any{"delete": operation("개인 Key Revoke", "")},
			"/me/activity":                                   get("내 접속/API/MCP 활동", ""),
			"/me/views":                                      methods("저장된 검색 조회 및 저장", "", ""),
			"/me/views/{id}":                                 map[string]any{"put": operation("저장된 검색 수정", ""), "delete": operation("저장된 검색 삭제", "")},
			"/me/favorites":                                  methods("즐겨찾기 조회 및 토글", "", ""),
			"/me/sessions":                                   get("내 로그인 Session", ""),
			"/me/sessions/{id}":                              map[string]any{"delete": operation("Session 폐기", "")},
			"/admin/settings":                                get("관리자 설정 목록", "admin:read"),
			"/admin/settings/{namespace}/{key}":              map[string]any{"put": operation("관리자 설정 변경", "admin:write"), "delete": operation("관리자 설정 삭제 및 기본값 복원", "admin:write")},
			"/admin/oidc":                                    readUpdate("Keycloak OIDC 설정", "admin:read", "admin:write"),
			"/admin/oidc/test":                               map[string]any{"post": operation("OIDC 연결 테스트", "admin:write")},
			"/admin/oidc/mappings":                           readUpdate("OIDC Role·Group Claim 매핑", "admin:read", "admin:write"),
			"/admin/approval-policies":                       methods("승인 정책 조회 및 생성", "admin:read", "admin:write"),
			"/admin/approval-policies/{id}":                  map[string]any{"put": operation("승인 정책 변경", "admin:write"), "delete": operation("승인 정책 삭제 또는 비활성화", "admin:write")},
			"/admin/users":                                   methods("사용자 조회 및 생성", "admin:read", "admin:write"),
			"/admin/users/{id}":                              map[string]any{"put": operation("사용자 정보 변경", "admin:write"), "delete": operation("사용자 비활성화 및 Session·Key 폐기", "admin:write")},
			"/admin/users/{id}/roles":                        map[string]any{"put": operation("사용자 Role 부여", "admin:write")},
			"/admin/users/{id}/password":                     map[string]any{"post": operation("로컬 사용자 임시 비밀번호 재설정", "admin:write")},
			"/admin/roles":                                   methods("Role 조회 및 생성", "admin:read", "admin:write"),
			"/admin/roles/{id}":                              map[string]any{"put": operation("Role 권한·Data Scope 변경", "admin:write"), "delete": operation("Role 삭제", "admin:write")},
			"/admin/permissions":                             get("부여 가능한 Function Permission 카탈로그", "admin:read"),
			"/admin/organizations":                           methods("조직 조회 및 생성", "admin:read", "admin:write"),
			"/admin/organizations/{id}":                      map[string]any{"put": operation("조직 변경", "admin:write"), "delete": operation("조직 삭제", "admin:write")},
			"/admin/custom-fields":                           methods("Custom Field 조회 및 생성", "admin:read", "admin:write"),
			"/admin/custom-fields/{id}":                      map[string]any{"put": operation("Custom Field 변경", "admin:write"), "delete": operation("Custom Field 정의 삭제", "admin:write")},
			"/admin/pipelines":                               methods("Pipeline 조회 및 생성", "admin:read", "admin:write"),
			"/admin/pipelines/{id}":                          map[string]any{"put": operation("Pipeline 변경", "admin:write"), "delete": operation("Pipeline 삭제", "admin:write")},
			"/admin/pipelines/{id}/stages":                   map[string]any{"post": operation("Pipeline Stage 추가", "admin:write")},
			"/admin/stages/{id}":                             map[string]any{"put": operation("Pipeline Stage 변경 및 순서 재배치", "admin:write"), "delete": operation("Pipeline Stage 삭제", "admin:write")},
			"/admin/audit":                                   get("필터·검색 가능한 감사 로그", "admin:read"),
			"/admin/operations":                              get("운영 준비도·진단·조치 센터", "admin:read"),
			"/admin/operations/support-bundle":               get("비밀값을 제외한 운영 Support Bundle", "admin:read"),
			"/admin/data-quality":                            get("CRM 데이터 품질 Score·문제·표본", "admin:read"),
			"/admin/configuration/export":                    get("Secret 제외 관리자 Configuration Bundle", "admin:read"),
			"/admin/configuration/preview":                   map[string]any{"post": operation("Configuration Bundle Diff 사전 검증", "admin:read")},
			"/admin/configuration/apply":                     map[string]any{"post": operation("검증된 Configuration Bundle 비파괴 적용", "admin:write")},
			"/admin/personal-keys":                           get("Personal Key Metadata", "admin:read"),
			"/admin/personal-keys/{id}":                      map[string]any{"delete": operation("Personal Key 강제 폐기", "admin:write")},
			"/admin/users/{id}/keys/revoke-all":              map[string]any{"post": operation("사용자 전체 Key 폐기", "admin:write")},
			"/admin/sales-execution":                         get("Stage Playbook 및 Exit Criteria", "admin:read"),
			"/admin/stages/{id}/sales-execution":             map[string]any{"put": operation("Sales Execution 정책 저장", "admin:write")},
			"/admin/deal-health-rules":                       get("Deal Health Rule 목록", "admin:read"),
			"/admin/deal-health-rules/{id}":                  map[string]any{"put": operation("Deal Health Rule 변경", "admin:write")},
		},
	}
}
func get(summary string, permission any) map[string]any {
	return map[string]any{"get": operation(summary, permission)}
}
func methods(summary, read, write string) map[string]any {
	return map[string]any{"get": operation(summary, read), "post": operation(summary, write)}
}

func readUpdate(summary, read, write string) map[string]any {
	return map[string]any{"get": operation(summary, read), "put": operation(summary, write)}
}
func readUpdateDelete(summary, read, write, remove string) map[string]any {
	return map[string]any{"get": operation(summary, read), "put": operation(summary, write), "delete": operation(summary, remove)}
}

func operation(summary string, permission any) map[string]any {
	return map[string]any{"summary": summary, "description": func() string {
		if p, ok := permission.(string); ok && p != "" {
			return "Required scope: " + p
		}
		return ""
	}(), "responses": map[string]any{"200": map[string]any{"description": "Success"}, "400": map[string]any{"description": "Invalid request"}, "401": map[string]any{"description": "Authentication required"}, "403": map[string]any{"description": "Permission denied"}}}
}
