import { FormEvent, useEffect, useMemo, useState } from 'react'
import { api, currencyMoney, date, money, number, relative } from '../api'
import { activityIcon, contactRoleLabel, initials, label } from '../labels'
import { Activity, Approval, Contract, Customer, Opportunity, Pipeline, RevenueSchedule, User, Version } from '../types'
import Layout, { Confirm, Empty, Link, Modal, Spinner, Status, navigate, rowProps, useDialog } from '../components/Layout'
import { errorMessage } from '../App'
import { ContactsPanel, useContacts } from '../components/Contacts'
import { DecideRecommendation, IntelligencePanel, Recommendation as RecommendationItem, RecommendationCard } from '../components/Intelligence'
import { VoicePanel } from './VoicePages'
import { FavoriteStar, SavedViews, useFavorites } from '../components/SavedViews'

type Props={path:string;user:User;version:Version;approvalEnabled:boolean;onLogout:()=>void;notify:(m:string,e?:boolean)=>void}
export default function AppPages(props:Props){
  const p=props.path
  if(p.startsWith('/app/customers/'))return <CustomerDetailV12 {...props} id={p.split('/')[3]}/>
  if(p==='/app/customers')return <Customers {...props}/>
  if(p==='/app/opportunities')return <Opportunities {...props}/>
  if(p==='/app/pipeline')return <PipelineBoard {...props}/>
  if(p==='/app/intelligence')return <DealIntelligence {...props}/>
  if(p==='/app/activities')return <Activities {...props}/>
  if(p==='/app/forecast')return <ForecastV11 {...props}/>
  if(p==='/app/contracts')return <Contracts {...props}/>
  if(p==='/app/approvals'&&props.approvalEnabled)return <Approvals {...props}/>
  return <Dashboard {...props}/>
}

function Frame({children,title,subtitle,actions,...props}:Props&{children:React.ReactNode;title:string;subtitle?:string;actions?:React.ReactNode}){return <Layout area="app" {...props} title={title} subtitle={subtitle} actions={actions}>{children}</Layout>}
const baseOpportunityAmount=(o:Opportunity)=>o.baseExpectedAmount??o.expectedAmount
const baseOpportunityWeighted=(o:Opportunity)=>o.baseWeightedAmount??o.weightedAmount

function Dashboard(props:Props){const [metrics,setMetrics]=useState<Record<string,number>|null>(null);const [opps,setOpps]=useState<Opportunity[]>([]);const [activities,setActivities]=useState<Activity[]>([]);const [today,setToday]=useState<TodayFeed|null>(null);useEffect(()=>{Promise.all([api<Record<string,number>>('/api/v1/dashboard'),api<{items:Opportunity[]}>('/api/v1/opportunities?limit=6'),api<{items:Activity[]}>('/api/v1/activities?limit=6')]).then(([m,o,a])=>{setMetrics(m);setOpps(o.items);setActivities(a.items)}).catch(e=>props.notify(errorMessage(e),true));api<TodayFeed>('/api/v1/today').then(setToday).catch(()=>{})},[]);return <Frame {...props} title={`${props.user.displayName}님, 좋은 하루예요`} subtitle="영업 현황과 오늘 집중할 일을 한눈에 확인하세요." actions={<><span className="date-chip">{new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date())}</span></>}>
    {!metrics?<Spinner/>:<><div className="kpi-grid"><KPI label="전체 고객" value={number(metrics.customerCount)} foot="내 데이터 범위" tone="blue" icon="◫"/><KPI label="진행 영업기회" value={number(metrics.openOpportunities)} foot={`${metrics.staleOpportunities||0}건 점검 필요`} tone="violet" icon="◆"/><KPI label="파이프라인 금액" value={money(metrics.pipelineAmount)} foot={`가중 ${money(metrics.weightedAmount)}`} tone="teal" icon="↗"/><KPI label="이번 달 수주" value={money(metrics.wonThisMonth)} foot={`${metrics.dueActions||0}개 후속 작업`} tone="amber" icon="✓"/></div>
    <TodayQueue feed={today}/>
    <DashboardRecommendations notify={props.notify} canWrite={props.user.isBootstrap||(props.user.permissions||[]).some(x=>x==='admin:*'||x==='intelligence:write')}/>
    <div className="dashboard-grid"><section className="panel span-2"><div className="panel-head"><div><h2>진행 중인 영업기회</h2><p>최근 수정 순 · 원화 기준</p></div><Link to="/app/pipeline">파이프라인 전체보기 →</Link></div>{opps.length?<div className="deal-list">{opps.map(o=><button key={o.id} className="deal-row" onClick={()=>navigate('/app/opportunities')}><span className="customer-logo">{initials(o.customerName, 2)}</span><span className="deal-name"><b>{o.name}</b><small>{o.customerName} · {o.ownerName}</small></span><span><Status value={o.forecastCategory}/></span><span className="deal-amount"><b>{currencyMoney(o.expectedAmount,o.currencyCode||'KRW')}</b><small>기준 {money(baseOpportunityAmount(o))}</small></span><span className="stage-pill" style={{'--stage':o.stageColor} as React.CSSProperties}>{o.stageName}</span></button>)}</div>:<Empty title="진행 영업건이 없습니다" description="첫 Opportunity를 생성해 Pipeline을 시작하세요." action={<button className="btn btn-primary" onClick={()=>navigate('/app/opportunities?new=1')}>영업기회 생성</button>}/>}</section>
    <section className="panel"><div className="panel-head"><div><h2>최근 활동</h2><p>팀의 고객 접점</p></div><Link to="/app/activities">전체보기</Link></div>{activities.length?<div className="timeline compact">{activities.map(a=><div className="timeline-item" key={a.id}><span className={`timeline-dot type-${a.activityType.toLowerCase()}`}>{activityIcon(a.activityType)}</span><div><b>{a.subject}</b><p>{a.ownerName} · {relative(a.occurredAt)}</p></div></div>)}</div>:<Empty icon="◷" title="최근 활동이 없습니다" description="미팅이나 통화를 기록해보세요."/>}</section></div></>}
  </Frame>}

/** DashboardRecommendations is the analysis speaking on the screen people
 *  actually open every morning. It shows at most three and links to the rest. */
function DashboardRecommendations({notify,canWrite}:{notify:Props['notify'];canWrite:boolean}){
  const [items,setItems]=useState<RecommendationItem[]|null>(null)
  const [deciding,setDeciding]=useState<{item:RecommendationItem;mode:'accept'|'dismiss'}|null>(null)
  const load=()=>api<{items:RecommendationItem[]}>('/api/v1/recommendations?mine=true&status=OPEN&limit=10')
    .then(v=>setItems(v.items)).catch(()=>setItems([]))
  useEffect(()=>{void load()},[])
  if(!items||!items.length)return null
  return <section className="panel recommendation-strip">
    <div className="panel-head"><div><h2>분석이 제안하는 다음 행동</h2><p>수락하면 내 할 일로 등록됩니다.</p></div>
      <Link to="/app/recommendations">{items.length}건 전체보기 →</Link></div>
    <div className="recommendation-grid">{items.slice(0,3).map(item=>
      <RecommendationCard key={item.id} item={item} canWrite={canWrite} showAccount onDecide={mode=>setDeciding({item,mode})}/>)}</div>
    {deciding&&<DecideRecommendation {...deciding} onClose={()=>setDeciding(null)}
      onDone={()=>{setDeciding(null);void load()}} notify={notify}/>}
  </section>
}

type TodayItem={kind:string;severity:string;title:string;subtitle:string;route:string;dueAt?:string}
type CustomerRiskFactor={code:string;label:string;detail:string;points:number;route?:string}
type CustomerRiskSummary={customerId:string;customerName:string;score:number;level:string;factors:CustomerRiskFactor[];recommendedAction?:string}
type TodayFeed={items:TodayItem[];counts:Record<string,number>;risks:CustomerRiskSummary[]}
const kindIcon:Record<string,string>={VOICE_OVERDUE:'!',NEXT_ACTION_DUE:'◷',DEAL_STALLED:'◆',RENEWAL_NOT_STARTED:'▤',APPROVAL_PENDING:'✓'}
const kindLabel:Record<string,string>={VOICE_OVERDUE:'고객 요청 기한 초과',NEXT_ACTION_DUE:'다음 행동 기한',DEAL_STALLED:'영업기회 정체',RENEWAL_NOT_STARTED:'갱신 미착수',APPROVAL_PENDING:'검토 대기'}

/** TodayQueue answers "무엇부터 하지?" — one ranked list across every subsystem
 *  that generates work, instead of leaving the user to infer it from metrics. */
function TodayQueue({feed}:{feed:TodayFeed|null}){
  if(!feed)return null
  const urgent=(feed.counts.CRITICAL||0)+(feed.counts.HIGH||0)
  return <div className="today-grid">
    <section className="panel today-panel">
      <div className="panel-head"><div><h2>오늘 먼저 할 일</h2><p>{feed.items.length?`${feed.items.length}건 · 즉시 대응 ${urgent}건`:'지금 밀린 일이 없습니다'}</p></div>
        {urgent>0&&<span className="count-badge danger">{urgent}</span>}</div>
      {feed.items.length?<div className="today-list">{feed.items.slice(0,8).map((item,i)=>
        <button key={i} onClick={()=>navigate(item.route)}>
          <span className={`today-mark sev-${item.severity.toLowerCase()}`}>{kindIcon[item.kind]||'·'}</span>
          <span className="today-copy"><b>{item.title}</b><small>{item.subtitle}</small></span>
          <span className="today-meta"><em>{kindLabel[item.kind]||item.kind}</em>{item.dueAt&&<small>{date(item.dueAt)}</small>}</span>
        </button>)}</div>
        :<Empty icon="✓" title="밀린 일이 없습니다" description="기한을 넘긴 고객 요청, 정체된 영업기회, 미착수 갱신이 모두 없습니다."/>}
    </section>
    <section className="panel risk-panel">
      <div className="panel-head"><div><h2>이탈 위험 고객</h2><p>요청·갱신·접점을 합산한 신호</p></div>
        <button onClick={()=>navigate('/app/voices')}>고객의 목소리 →</button></div>
      {feed.risks.length?<div className="risk-list">{feed.risks.map(r=>
        <button key={r.customerId} onClick={()=>navigate('/app/customers/'+r.customerId)}>
          <span className={`risk-score level-${r.level.toLowerCase()}`}>{r.score}</span>
          <span className="risk-copy"><b>{r.customerName}</b><small>{r.factors.slice(0,2).map(f=>f.label).join(' · ')}</small></span>
          <Status value={r.level}/>
        </button>)}</div>
        :<Empty icon="♡" title="위험 신호가 없습니다" description="미해결 요청, 임박한 갱신, 접점 공백이 발견되지 않았습니다."/>}
    </section>
  </div>
}

function KPI({label,value,foot,tone,icon}:{label:string;value:string;foot:string;tone:string;icon:string}){return <article className={`kpi-card tone-${tone}`}><div className="kpi-top"><span className="kpi-icon">{icon}</span><span className="trend">실시간</span></div><p>{label}</p><strong>{value}</strong><small>{foot}</small></article>}

// customerQuery describes the current filter so it can be saved and replayed.
const customerQuery=({query,customerType,grade}:{query:string;customerType:string;grade:string})=>{
  const q=new URLSearchParams()
  if(query)q.set('q',query)
  if(customerType)q.set('customerType',customerType)
  if(grade)q.set('grade',grade)
  return q.toString()
}

function Customers(props:Props){
  const params=new URLSearchParams(location.search)
  const [items,setItems]=useState<Customer[]>([]);const [loading,setLoading]=useState(true)
  const [query,setQuery]=useState(params.get('q')||'');const [customerType,setCustomerType]=useState('');const [grade,setGrade]=useState('')
  const [modal,setModal]=useState<null|{customer?:Customer}>(params.get('new')==='1'?{}:null)
  const favorites=useFavorites('CUSTOMER')
  const load=(filters?:{customerType?:string;grade?:string;query?:string})=>{setLoading(true)
    const q=new URLSearchParams({q:filters?.query??query});const type=filters?.customerType??customerType;const g=filters?.grade??grade
    if(type)q.set('customerType',type);if(g)q.set('grade',g)
    return api<{items:Customer[]}>('/api/v1/customers?'+q.toString()).then(v=>setItems(v.items)).catch(e=>props.notify(errorMessage(e),true)).finally(()=>setLoading(false))}
  useEffect(()=>{void load()},[])
  const pick=(setter:(v:string)=>void,key:'customerType'|'grade')=>(value:string)=>{setter(value);void load({[key]:value})}
  return <Frame {...props} title="고객" subtitle="첫 접점부터 누적 매출까지 고객 360으로 관리합니다." actions={<button className="btn btn-primary" onClick={()=>setModal({})}>＋ 고객 등록</button>}>
    <form className="toolbar" onSubmit={e=>{e.preventDefault();void load()}}>
      <div className="filter-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="고객명 또는 사업자번호 검색"/></div>
      <button className="btn btn-secondary">검색</button>
      <select value={customerType} onChange={e=>pick(setCustomerType,'customerType')(e.target.value)} aria-label="고객유형 필터"><option value="">전체 고객유형</option><option value="PROSPECT">잠재 고객</option><option value="CUSTOMER">거래 고객</option><option value="PARTNER">파트너</option></select>
      <select value={grade} onChange={e=>pick(setGrade,'grade')(e.target.value)} aria-label="고객등급 필터"><option value="">전체 등급</option><option>A</option><option>B</option><option>C</option></select>
      {(customerType||grade||query)&&<button type="button" className="btn btn-ghost" onClick={()=>{setQuery('');setCustomerType('');setGrade('');void load({customerType:'',grade:''})}}>필터 초기화</button>}
      <span className="toolbar-count">총 {items.length}개</span>
    </form>
    <SavedViews resource="CUSTOMER" current={customerQuery({query,customerType,grade})} notify={props.notify}
      onApply={q=>{const p=new URLSearchParams(q);const nq=p.get('q')||'';const nt=p.get('customerType')||'';const ng=p.get('grade')||'';
        setQuery(nq);setCustomerType(nt);setGrade(ng);void load({customerType:nt,grade:ng,query:nq})}}/>
    <section className="panel table-panel">{loading?<Spinner/>:items.length?<table><thead><tr><th aria-label="즐겨찾기"/><th>고객</th><th>구분 · 등급</th><th>산업</th><th>담당 영업</th><th>건강도</th><th>최근 수정</th><th>관리</th></tr></thead><tbody>{items.map(c=><tr key={c.id} {...rowProps(()=>navigate('/app/customers/'+c.id))} aria-label={`${c.name} 고객 360 열기`}>
      <td><FavoriteStar resource="CUSTOMER" resourceId={c.id} favorited={favorites.ids.has(c.id)} onChange={on=>favorites.set(c.id,on)} notify={props.notify}/></td>
      <td><div className="entity-cell"><span className="customer-logo">{initials(c.name, 2)}</span><span><b>{c.name}</b><small>{c.registrationNo||c.email||'식별 정보 없음'}</small></span></div></td>
      <td><Status value={c.customerType}/>{c.grade&&<span className="grade">{c.grade}</span>}</td>
      <td>{c.industry||'—'}</td>
      <td>{c.ownerName}</td>
      <td><Status value={c.health}/></td>
      <td>{relative(c.updatedAt)}</td>
      <td><div className="row-menu"><button onClick={()=>setModal({customer:c})}>편집</button><button onClick={()=>navigate('/app/customers/'+c.id)}>360 →</button></div></td>
    </tr>)}</tbody></table>:<Empty icon="◫" title={query||customerType||grade?'조건에 맞는 고객이 없습니다':'아직 등록된 고객이 없습니다'} description={query||customerType||grade?'검색어나 필터를 바꿔 다시 시도하세요.':'고객을 등록하고 관계 정보를 한 곳에서 관리하세요.'} action={<button className="btn btn-primary" onClick={()=>setModal({})}>고객 등록</button>}/>}</section>
    {modal&&<CustomerModal customer={modal.customer} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);void load()}} notify={props.notify}/>}
  </Frame>
}
function CustomerModal({customer,onClose,onSaved,notify}:{customer?:Customer;onClose:()=>void;onSaved:()=>void;notify:Props['notify']}){
  const editing=Boolean(customer?.id);const [busy,setBusy]=useState(false)
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true)
    const body={name:f.get('name'),registrationNo:f.get('registrationNo'),customerType:f.get('customerType'),grade:f.get('grade'),industry:f.get('industry'),website:f.get('website'),phone:f.get('phone'),email:f.get('email'),address:f.get('address'),health:f.get('health')||'NORMAL',annualRevenue:Number(f.get('annualRevenue')||0),employeeCount:Number(f.get('employeeCount')||0),customFields:customer?.customFields||{},version:customer?.version||0}
    try{await api(editing?`/api/v1/customers/${customer!.id}`:'/api/v1/customers',{method:editing?'PUT':'POST',body:JSON.stringify(body)});notify(editing?'고객 정보를 저장했습니다.':'고객이 등록되었습니다.');onSaved()}catch(e){notify(errorMessage(e),true)}finally{setBusy(false)}}
  return <Modal title={editing?`${customer!.name} 편집`:'새 고객 등록'} onClose={onClose} wide><form onSubmit={submit} className="form"><div className="form-grid">
    <label className="span-2">고객사명 *<input name="name" required autoFocus defaultValue={customer?.name||''} placeholder="예: (주)릴리오테크"/></label>
    <label>사업자번호<input name="registrationNo" defaultValue={customer?.registrationNo||''} placeholder="000-00-00000"/></label>
    <label>고객 구분<select name="customerType" defaultValue={customer?.customerType||'PROSPECT'}><option value="PROSPECT">잠재 고객</option><option value="CUSTOMER">거래 고객</option><option value="PARTNER">파트너</option></select></label>
    <label>고객 등급<select name="grade" defaultValue={customer?.grade||''}><option value="">미지정</option><option>A</option><option>B</option><option>C</option></select></label>
    <label>산업<input name="industry" defaultValue={customer?.industry||''} placeholder="제조, IT, 금융…"/></label>
    <label>대표 전화<input name="phone" defaultValue={customer?.phone||''}/></label>
    <label>대표 이메일<input name="email" type="email" defaultValue={customer?.email||''}/></label>
    <label>홈페이지<input name="website" defaultValue={customer?.website||''} placeholder="https://"/></label>
    <label>건강도<select name="health" defaultValue={customer?.health||'NORMAL'}><option value="GOOD">GOOD</option><option value="NORMAL">NORMAL</option><option value="RISK">RISK</option></select></label>
    <label className="span-2">주소<input name="address" defaultValue={customer?.address||''}/></label>
    <label>연 매출<input name="annualRevenue" type="number" min="0" defaultValue={customer?.annualRevenue??0}/></label>
    <label>임직원 수<input name="employeeCount" type="number" min="0" defaultValue={customer?.employeeCount??0}/></label>
  </div><div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={onClose}>취소</button><button className="btn btn-primary" disabled={busy}>{busy?'저장 중…':editing?'변경 저장':'고객 등록'}</button></div></form></Modal>
}


/** CustomerRiskBand shows why a customer is at risk, not just that they are. */
function CustomerRiskBand({customerId}:{customerId:string}){
  const [risk,setRisk]=useState<CustomerRiskSummary|null>(null)
  useEffect(()=>{api<CustomerRiskSummary>(`/api/v1/customers/${customerId}/risk`).then(setRisk).catch(()=>{})},[customerId])
  if(!risk||!risk.factors.length)return null
  return <section className={`panel risk-band level-${risk.level.toLowerCase()}`}>
    <div className="risk-band-score"><strong>{risk.score}</strong><small>이탈 위험도</small><Status value={risk.level}/></div>
    <div className="risk-band-factors">{risk.factors.map(f=><div key={f.code}>
      <b>{f.label}</b><small>{f.detail}</small><em>+{f.points}</em></div>)}</div>
    {risk.recommendedAction&&<div className="risk-band-action"><b>권장 행동</b><p>{risk.recommendedAction}</p></div>}
  </section>
}

function Metric({label,value}:{label:string;value:string}){return <div><small>{label}</small><b>{value}</b></div>}

function Opportunities(props:Props){
  const [items,setItems]=useState<Opportunity[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [pipelines,setPipelines]=useState<Pipeline[]>([]);const [loading,setLoading]=useState(true);const [modal,setModal]=useState(new URLSearchParams(location.search).get('new')==='1');const [selected,setSelected]=useState<Opportunity|null>(null)
  const [query,setQuery]=useState('');const [stage,setStage]=useState('');const [forecast,setForecast]=useState('')
  const load=()=>{setLoading(true);const params=new URLSearchParams({limit:'100'});if(query.trim())params.set('q',query.trim());if(stage)params.set('stageId',stage);if(forecast)params.set('forecastCategory',forecast);return Promise.all([api<{items:Opportunity[]}>(`/api/v1/opportunities?${params}`),api<{items:Customer[]}>('/api/v1/customers?limit=200'),api<{items:Pipeline[]}>('/api/v1/pipeline')]).then(([o,c,p])=>{setItems(o.items);setCustomers(c.items);setPipelines(p.items)}).catch(e=>props.notify(errorMessage(e),true)).finally(()=>setLoading(false))}
  useEffect(()=>{void load()},[])
  const total=items.reduce((sum,item)=>sum+baseOpportunityAmount(item),0)
  return <Frame {...props} title="영업기회" subtitle="거래통화는 보존하고 원화 기준금액으로 일관된 매출 전망을 만듭니다." actions={<button className="btn btn-primary" onClick={()=>setModal(true)}>＋ 영업기회 생성</button>}><form className="toolbar" onSubmit={e=>{e.preventDefault();void load()}}><div className="filter-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Opportunity 또는 고객 검색"/></div><select value={stage} onChange={e=>setStage(e.target.value)}><option value="">전체 단계</option>{pipelines.flatMap(p=>p.stages).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><select value={forecast} onChange={e=>setForecast(e.target.value)}><option value="">전체 전망</option>{['COMMIT','BEST_CASE','PIPELINE'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><button className="btn btn-secondary">적용</button><span className="toolbar-count">{items.length}건 · 기준 {money(total)}</span></form><section className="panel table-panel">{loading?<Spinner/>:items.length?<table><thead><tr><th>영업기회</th><th>고객</th><th>단계</th><th>거래 금액 · 기준금액</th><th>매출 전망</th><th>예상 계약일</th><th>건강도</th></tr></thead><tbody>{items.map(o=><tr key={o.id} {...rowProps(()=>setSelected(o))} aria-label={`${o.name} 상세 열기`}><td><b>{o.name}</b><small className="table-sub">{o.ownerName}</small></td><td>{o.customerName}</td><td><span className="stage-pill" style={{'--stage':o.stageColor} as React.CSSProperties}>{o.stageName} · {o.probability}%</span></td><td><b>{currencyMoney(o.expectedAmount,o.currencyCode||'KRW')}</b><small className="table-sub">기준 {money(baseOpportunityAmount(o))} · 가중 {money(baseOpportunityWeighted(o))}</small></td><td><Status value={o.forecastCategory}/></td><td>{date(o.expectedCloseDate)}</td><td>{(o.health||[]).length?<span className="health-warning" title={(o.health||[]).join(', ')}>! {(o.health||[]).length}</span>:<span className="health-good">✓</span>}</td></tr>)}</tbody></table>:<Empty title="조건에 맞는 영업기회가 없습니다" description="검색 조건을 바꾸거나 새 영업기회를 생성하세요."/>}</section>{modal&&<OpportunityModal customers={customers} pipelines={pipelines} onClose={()=>setModal(false)} onSaved={()=>{setModal(false);load()}} notify={props.notify}/>} {selected&&<OpportunityDrawerV11 opportunity={selected} approvalEnabled={props.approvalEnabled} notify={props.notify} canIntelligenceWrite={props.user.isBootstrap||(props.user.permissions||[]).some(x=>x==='admin:*'||x==='intelligence:write')} onClose={()=>setSelected(null)} onUpdated={()=>{setSelected(null);load()}}/>}</Frame>
}

function OpportunityModal({customers,pipelines,onClose,onSaved,notify}:{customers:Customer[];pipelines:Pipeline[];onClose:()=>void;onSaved:()=>void;notify:Props['notify']}){const stages=pipelines.find(p=>p.default)?.stages||pipelines[0]?.stages||[];const [busy,setBusy]=useState(false);const [currency,setCurrency]=useState('KRW');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api('/api/v1/opportunities',{method:'POST',body:JSON.stringify({name:f.get('name'),customerId:f.get('customerId'),stageId:f.get('stageId'),expectedAmount:Number(f.get('amount')),currencyCode:currency,exchangeRate:currency==='KRW'?1:Number(f.get('exchangeRate')),expectedCloseDate:f.get('closeDate')||null,nextAction:f.get('nextAction'),nextActionDate:f.get('nextActionDate')||null,customFields:{}})});notify('Opportunity가 생성되었습니다.');onSaved()}catch(e){notify(errorMessage(e),true)}finally{setBusy(false)}}return <Modal title="새 영업기회" onClose={onClose} wide><form className="form" onSubmit={submit}><div className="form-grid"><label className="span-2">영업기회 이름 *<input name="name" required autoFocus placeholder="예: 2026 통합 CRM 구축"/></label><label>고객 *<select name="customerId" required><option value="">고객 선택</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>단계<select name="stageId">{stages.map(s=><option value={s.id} key={s.id}>{s.name} · {s.probability}%</option>)}</select></label><label>예상 금액<input name="amount" type="number" min="0" step="0.01" defaultValue="0"/></label><label>거래 통화<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>KRW</option><option>USD</option><option>EUR</option><option>JPY</option><option>CNY</option><option>GBP</option></select></label>{currency!=='KRW'&&<label className="span-2">고정 환율 · 1 {currency}당 KRW<input name="exchangeRate" type="number" min="0.00000001" step="0.00000001" required/><small>전망 재현성을 위해 생성 시점 환율을 거래에 고정합니다.</small></label>}<label>예상 계약일<input name="closeDate" type="date"/></label><label className="span-2">다음 행동<input name="nextAction" placeholder="예: 기술 제안서 전달"/></label><label>다음 행동일<input name="nextActionDate" type="date"/></label></div><div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={onClose}>취소</button><button className="btn btn-primary" disabled={busy}>{busy?'생성 중…':'영업기회 생성'}</button></div></form></Modal>}


function PipelineBoard(props:Props){const [pipelines,setPipelines]=useState<Pipeline[]>([]);const [items,setItems]=useState<Opportunity[]>([]);const [loading,setLoading]=useState(true);const load=()=>Promise.all([api<{items:Pipeline[]}>('/api/v1/pipeline'),api<{items:Opportunity[]}>('/api/v1/opportunities?status=OPEN&limit=200')]).then(([p,o])=>{setPipelines(p.items);setItems(o.items)}).catch(e=>props.notify(errorMessage(e),true)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);const pipe=pipelines.find(p=>p.default)||pipelines[0];async function drop(e:React.DragEvent,stageId:string){e.preventDefault();const id=e.dataTransfer.getData('text/relio-id');const deal=items.find(x=>x.id===id);if(!deal||deal.stageId===stageId)return;setItems(v=>v.map(x=>x.id===id?{...x,stageId}:x));try{await api(`/api/v1/opportunities/${id}/stage`,{method:'POST',body:JSON.stringify({stageId,version:deal.version})});props.notify('Stage를 변경했습니다.');load()}catch(err){props.notify(errorMessage(err),true);load()}}return <Frame {...props} title="영업 파이프라인" subtitle="원화 기준으로 비교하되 거래통화 원금은 각 영업기회에 보존합니다." actions={<div className="segmented"><button className="active">칸반</button><button onClick={()=>navigate('/app/opportunities')}>목록</button></div>}>{loading?<Spinner/>:pipe?<><div className="pipeline-summary"><Metric label="진행 영업기회" value={`${items.length}건`}/><Metric label="Pipeline" value={money(items.reduce((a,b)=>a+baseOpportunityAmount(b),0))}/><Metric label="Weighted" value={money(items.reduce((a,b)=>a+baseOpportunityWeighted(b),0))}/><Metric label="Stale" value={`${items.filter(x=>(x.health||[]).includes('STAGE_STALLED')).length}건`}/></div><div className="kanban">{pipe.stages.filter(s=>!s.isWon&&!s.isLost).map(stage=>{const deals=items.filter(o=>o.stageId===stage.id);return <section className="kanban-column" key={stage.id} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,stage.id)}><header><span className="stage-dot" style={{background:stage.color}}/><b>{stage.name}</b><em>{deals.length}</em><small>{money(deals.reduce((a,b)=>a+baseOpportunityAmount(b),0))}</small></header><div className="kanban-body">{deals.map(o=><article draggable onDragStart={e=>e.dataTransfer.setData('text/relio-id',o.id)} className="deal-card" key={o.id}><div className="deal-card-top"><span>{o.customerName}</span>{(o.health||[]).length>0&&<i>!</i>}</div><h3>{o.name}</h3><strong>{currencyMoney(o.expectedAmount,o.currencyCode||'KRW')}</strong><div className="deal-progress"><span style={{width:`${o.probability}%`,background:stage.color}}/></div><footer><span className="avatar tiny">{initials(o.ownerName, 1)}</span><span>{date(o.expectedCloseDate)}</span></footer></article>)}</div></section>})}</div></>:<Empty title="영업 단계 설정이 없습니다" description="관리자 콘솔에서 Pipeline과 Stage를 설정하세요."/>}</Frame>}

const activityTypes:[string,string,string][]=[['','전체 활동','◉'],['MEETING','미팅','♟'],['CALL','전화','☎'],['EMAIL','이메일','✉'],['VISIT','방문','⌂'],['NOTE','메모','▤']]
function Activities(props:Props){
  const [items,setItems]=useState<Activity[]>([]);const [loading,setLoading]=useState(true);const [type,setType]=useState('')
  const [modal,setModal]=useState(new URLSearchParams(location.search).has('new'))
  const load=(next=type)=>{setLoading(true);return api<{items:Activity[]}>('/api/v1/activities?limit=100'+(next?'&type='+next:'')).then(v=>setItems(v.items)).catch(e=>props.notify(errorMessage(e),true)).finally(()=>setLoading(false))}
  useEffect(()=>{void load()},[])
  const choose=(next:string)=>{setType(next);void load(next)}
  return <Frame {...props} title="영업활동" subtitle="고객과의 모든 접점을 시간 순서로 연결합니다." actions={<button className="btn btn-primary" onClick={()=>setModal(true)}>＋ 활동 기록</button>}>
    <div className="activity-layout">
      <aside className="panel activity-filter"><h3>활동 유형</h3>{activityTypes.map(([value,label,glyph])=><button className={type===value?'active':''} key={label} onClick={()=>choose(value)}><span>{glyph}</span>{label}<em>{type===value?items.length:''}</em></button>)}</aside>
      <section className="panel"><div className="panel-head"><div><h2>활동 타임라인</h2><p>{type?`${activityTypes.find(x=>x[0]===type)?.[1]} 활동만 표시합니다`:'최신 활동부터 표시합니다'}</p></div></div>
        {loading?<Spinner/>:items.length?<div className="timeline large">{items.map(a=><div className="timeline-item" key={a.id}><span className={`timeline-dot type-${a.activityType.toLowerCase()}`}>{activityIcon(a.activityType)}</span><div className="timeline-card"><header><div><Status value={a.activityType}/><b>{a.subject}</b></div><time>{date(a.occurredAt)}</time></header>{a.description&&<p>{a.description}</p>}<footer><span className="avatar tiny">{initials(a.ownerName, 1)}</span>{a.ownerName}{a.nextAction&&<span className="next-action">→ {a.nextAction} · {date(a.nextActionDate)}</span>}{a.customerId&&<button className="activity-to-voice" title="이 접점에서 불만이나 요청이 나왔다면 바로 접수합니다" onClick={()=>navigate(`/app/voices?new=1&customerId=${a.customerId}&title=${encodeURIComponent(a.subject)}&body=${encodeURIComponent(a.description||'')}`)}>고객 요청으로 접수 →</button>}</footer></div></div>)}</div>
        :<Empty title={type?'해당 유형의 활동이 없습니다':'기록된 활동이 없습니다'} description={type?'다른 유형을 선택하거나 새 활동을 기록하세요.':'첫 고객 접점을 기록하세요.'}/>}</section>
    </div>
    {modal&&<ActivityModal onClose={()=>setModal(false)} onSaved={()=>{setModal(false);void load()}} notify={props.notify}/>}
  </Frame>
}
function ActivityModal({onClose,onSaved,notify}:{onClose:()=>void;onSaved:()=>void;notify:Props['notify']}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/v1/activities',{method:'POST',body:JSON.stringify({activityType:f.get('type'),subject:f.get('subject'),description:f.get('description'),occurredAt:new Date().toISOString(),nextAction:f.get('nextAction'),nextActionDate:f.get('nextDate')||null})});notify('영업활동을 기록했습니다.');onSaved()}catch(e){notify(errorMessage(e),true)}}return <Modal title="영업활동 기록" onClose={onClose}><form className="form" onSubmit={submit}><label>활동 유형<select name="type"><option value="MEETING">미팅</option><option value="CALL">전화</option><option value="EMAIL">이메일</option><option value="VISIT">방문</option><option value="NOTE">메모</option></select></label><label>제목 *<input name="subject" required autoFocus/></label><label>내용<textarea name="description" rows={4}/></label><label>다음 행동<input name="nextAction"/></label><label>다음 행동일<input type="date" name="nextDate"/></label><div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={onClose}>취소</button><button className="btn btn-primary">활동 저장</button></div></form></Modal>}

function Forecast(props:Props){const [data,setData]=useState<any>(null);const [kpi,setKpi]=useState<any>(null);useEffect(()=>{Promise.all([api('/api/v1/forecasts'),api('/api/v1/sales/kpi')]).then(([f,k])=>{setData(f);setKpi(k)}).catch(e=>props.notify(errorMessage(e),true))},[]);return <Frame {...props} title="매출 전망" subtitle="파이프라인의 가능성과 목표 달성 흐름을 함께 예측합니다.">{!data?<Spinner/>:<><div className="kpi-grid"><KPI label="전체 파이프라인" value={money(data.pipeline)} foot="Open Opportunity" tone="blue" icon="↗"/><KPI label="가중 전망" value={money(data.weighted)} foot="확률 가중 예상" tone="violet" icon="◆"/><KPI label="이번 달 매출" value={money(kpi?.revenueThisMonth)} foot={`목표 ${money(kpi?.target)}`} tone="teal" icon="✓"/><KPI label="목표 달성률" value={`${(kpi?.attainmentPercent||0).toFixed(1)}%`} foot="Current period" tone="amber" icon="◎"/></div><section className="panel forecast-board"><div className="panel-head"><div><h2>전망 분류</h2><p>현재 데이터 범위 기준</p></div><span className="date-chip">Generated {new Date(data.generatedAt).toLocaleTimeString('ko-KR')}</span></div><div className="forecast-bars">{data.categories.map((c:any)=>{const width=data.pipeline?Math.max(4,c.amount/data.pipeline*100):0;return <div key={c.category}><header><Status value={c.category}/><b>{money(c.amount)}</b><small>{c.count}건 · 가중 {money(c.weightedAmount)}</small></header><div><span style={{width:`${width}%`}}/></div></div>})}</div></section></>}</Frame>}
function Contracts(props:Props){
  const [items,setItems]=useState<Contract[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [opportunities,setOpportunities]=useState<Opportunity[]>([]);const [loading,setLoading]=useState(true);const [modal,setModal]=useState(false);const [selected,setSelected]=useState<Contract|null>(null);const [query,setQuery]=useState('');const [status,setStatus]=useState('');const [expiring,setExpiring]=useState(false)
  const load=()=>{setLoading(true);return Promise.all([api<{items:Contract[]}>(`/api/v1/contracts?limit=200${expiring?'&expiringDays=90':''}`),api<{items:Customer[]}>('/api/v1/customers?limit=200').catch(()=>({items:[]})),api<{items:Opportunity[]}>('/api/v1/opportunities?limit=200').catch(()=>({items:[]}))]).then(([contracts,c,o])=>{setItems(contracts.items);setCustomers(c.items);setOpportunities(o.items)}).catch(e=>props.notify(errorMessage(e),true)).finally(()=>setLoading(false))}
  useEffect(()=>{void load()},[expiring])
  const visible=items.filter(x=>(!status||x.radarStatus===status||x.status===status)&&(!query.trim()||`${x.contractNo} ${x.title} ${x.customerName}`.toLowerCase().includes(query.trim().toLowerCase())))
  const activeBase=items.filter(x=>x.status==='ACTIVE').reduce((sum,x)=>sum+x.baseAmount,0);const renewalDue=items.filter(x=>x.radarStatus==='EXPIRING').length;const dueRevenue=items.reduce((sum,x)=>sum+Math.max(0,x.scheduleCount-x.recognizedCount),0)
  return <Frame {...props} title="계약 · 매출 인식과 갱신 레이더" subtitle="계약 활성화부터 매출 이행과 갱신 다음 행동까지 한 흐름으로 관리합니다." actions={<button className="btn btn-primary" onClick={()=>setModal(true)}>＋ 계약 등록</button>}><div className="contract-kpis"><Metric label="활성 계약 기준금액" value={money(activeBase)}/><Metric label="90일 내 갱신 점검" value={`${renewalDue}건`}/><Metric label="미인식 매출 일정" value={`${dueRevenue}건`}/></div><div className="toolbar"><div className="filter-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="계약번호, 고객 또는 계약명 검색"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">전체 상태</option><option>DRAFT</option><option>ACTIVE</option><option>EXPIRING</option><option>EXPIRED</option></select><button className={`btn ${expiring?'btn-primary':'btn-secondary'}`} onClick={()=>setExpiring(v=>!v)}>90일 내 만료</button><span className="toolbar-count">{visible.length}건</span></div><section className="panel table-panel">{loading?<Spinner/>:visible.length?<table><thead><tr><th>계약번호</th><th>고객 · 계약명</th><th>거래금액 · 기준금액</th><th>계약 기간</th><th>매출 인식</th><th>갱신</th><th>갱신 레이더</th></tr></thead><tbody>{visible.map(x=><tr key={x.id} onClick={()=>setSelected(x)}><td><b>{x.contractNo}</b><small className="table-sub">{x.revenueScheduleType}</small></td><td><b>{x.title}</b><small className="table-sub">{x.customerName}</small></td><td><b>{currencyMoney(x.amount,x.currencyCode||'KRW')}</b><small className="table-sub">기준 {money(x.baseAmount)}</small></td><td>{date(x.startDate)} → {date(x.endDate)}<small className="table-sub">{x.daysToExpiry==null?'종료일 미정':x.daysToExpiry<0?`${Math.abs(x.daysToExpiry)}일 경과`:`D-${x.daysToExpiry}`}</small></td><td><b>{x.recognizedCount}/{x.scheduleCount}</b><small className="table-sub">인식 {money(x.recognizedBaseAmount)}</small></td><td><Status value={x.renewalStatus}/><small className="table-sub">{x.autoRenew?'자동 갱신':'일반 갱신'}</small></td><td><Status value={x.radarStatus||x.status}/></td></tr>)}</tbody></table>:<Empty icon="▤" title="조건에 맞는 계약이 없습니다" description="계약을 등록하거나 필터 조건을 변경하세요." action={<button className="btn btn-primary" onClick={()=>setModal(true)}>첫 계약 등록</button>}/>}</section>{modal&&<ContractModal customers={customers} opportunities={opportunities} onClose={()=>setModal(false)} onSaved={()=>{setModal(false);void load()}} notify={props.notify}/>} {selected&&<ContractDrawer contract={selected} onClose={()=>setSelected(null)} onUpdated={()=>{setSelected(null);void load()}} notify={props.notify}/>}</Frame>
}

function ContractModal({customers,opportunities,onClose,onSaved,notify}:{customers:Customer[];opportunities:Opportunity[];onClose:()=>void;onSaved:()=>void;notify:Props['notify']}){
  const [currency,setCurrency]=useState('KRW');const [customerId,setCustomerId]=useState('');const [busy,setBusy]=useState(false)
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api('/api/v1/contracts',{method:'POST',body:JSON.stringify({customerId,opportunityId:f.get('opportunityId')||'',title:f.get('title'),amount:Number(f.get('amount')),currencyCode:currency,exchangeRate:currency==='KRW'?1:Number(f.get('exchangeRate')),startDate:f.get('startDate'),endDate:f.get('endDate'),status:'DRAFT',autoRenew:f.get('autoRenew')==='on',revenueScheduleType:f.get('scheduleType'),renewalNoticeDays:Number(f.get('renewalNoticeDays')),renewalAction:f.get('renewalAction'),customFields:{}})});notify('계약 초안을 등록했습니다. 검토 후 활성화하면 매출 일정이 생성됩니다.');onSaved()}catch(e){notify(errorMessage(e),true)}finally{setBusy(false)}}
  return <Modal title="새 계약 등록" onClose={onClose} wide><form className="form" onSubmit={submit}><div className="form-grid"><label className="span-2">계약명 *<input name="title" required autoFocus placeholder="예: Enterprise CRM 연간 구독"/></label><label>고객 *<select required value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">고객 선택</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>연결 영업기회<select name="opportunityId"><option value="">미연결</option>{opportunities.filter(o=>!customerId||o.customerId===customerId).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>계약 금액 *<input name="amount" type="number" min="0" step="0.01" required/></label><label>거래 통화<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>KRW</option><option>USD</option><option>EUR</option><option>JPY</option><option>CNY</option><option>GBP</option></select></label>{currency!=='KRW'&&<label className="span-2">고정 환율 · 1 {currency}당 KRW<input name="exchangeRate" type="number" min="0.00000001" step="0.00000001" required/><small>계약 및 매출 일정 전체에 동일한 환율을 고정합니다.</small></label>}<label>계약 시작일 *<input name="startDate" type="date" required/></label><label>계약 종료일 *<input name="endDate" type="date" required/></label><label>매출 인식 주기<select name="scheduleType"><option value="ONE_TIME">일시 인식</option><option value="MONTHLY">월별</option><option value="QUARTERLY">분기별</option><option value="ANNUAL">연별</option></select></label><label>갱신 사전 알림<input name="renewalNoticeDays" type="number" min="0" max="730" defaultValue="90"/><small>종료일 기준 사전 점검 일수</small></label><label className="check-label"><input name="autoRenew" type="checkbox"/> 자동 갱신 조항</label><label className="span-2">갱신 다음 행동<input name="renewalAction" placeholder="예: 종료 120일 전 QBR 및 사용량 검토"/></label></div><div className="contract-flow-note"><b>초안 → 활성 → 매출 인식</b><span>활성화 시 계약 금액을 주기별로 분할하고, 일정 합계가 계약 원금과 정확히 일치하도록 소수 단위 오차를 보정합니다.</span></div><div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={onClose}>취소</button><button className="btn btn-primary" disabled={busy}>{busy?'등록 중…':'계약 초안 등록'}</button></div></form></Modal>
}

function ContractDrawer({contract,onClose,onUpdated,notify}:{contract:Contract;onClose:()=>void;onUpdated:()=>void;notify:Props['notify']}){
  const surface=useDialog(onClose)
  const [schedule,setSchedule]=useState<RevenueSchedule[]|null>(null);const [renewalStatus,setRenewalStatus]=useState(contract.renewalStatus);const [renewalAction,setRenewalAction]=useState(contract.renewalAction||'');const loadSchedule=()=>api<{items:RevenueSchedule[]}>(`/api/v1/contracts/${contract.id}/revenue-schedule`).then(v=>setSchedule(v.items)).catch(e=>notify(errorMessage(e),true));useEffect(()=>{void loadSchedule()},[contract.id])
  async function activate(){if(!confirm('계약을 활성화하고 매출 인식 일정을 생성할까요?'))return;try{await api(`/api/v1/contracts/${contract.id}/activate`,{method:'POST',body:JSON.stringify({version:contract.version})});notify('계약을 활성화하고 매출 일정을 생성했습니다.');onUpdated()}catch(e){notify(errorMessage(e),true)}}
  async function saveRenewal(){try{await api(`/api/v1/contracts/${contract.id}/renewal`,{method:'PUT',body:JSON.stringify({renewalStatus,renewalAction,version:contract.version})});notify('갱신 계획을 저장했습니다.');onUpdated()}catch(e){notify(errorMessage(e),true)}}
  async function recognize(item:RevenueSchedule){const recognizedDate=prompt('매출 인식일 (YYYY-MM-DD)',new Date().toLocaleDateString('en-CA'));if(!recognizedDate)return;try{await api(`/api/v1/revenue-schedules/${item.id}/recognize`,{method:'POST',body:JSON.stringify({recognizedDate})});notify('매출을 인식하고 Sales Ledger에 반영했습니다.');loadSchedule()}catch(e){notify(errorMessage(e),true)}}
  return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside ref={surface} className="drawer drawer-wide" role="dialog" aria-modal="true"><div className="drawer-head"><div><p className="eyebrow">CONTRACT · {contract.contractNo}</p><h2>{contract.title}</h2><p>{contract.customerName} · {contract.revenueScheduleType}</p></div><button className="icon-btn" onClick={onClose}>×</button></div><div className="drawer-body"><div className="amount-hero"><small>Contract Value · {contract.currencyCode}</small><strong>{currencyMoney(contract.amount,contract.currencyCode||'KRW')}</strong><span>기준 {money(contract.baseAmount)} · 고정환율 {number(contract.exchangeRate)}</span></div><div className="contract-state"><Status value={contract.radarStatus||contract.status}/><span>{date(contract.startDate)} → {date(contract.endDate)}</span>{contract.activatedAt&&<small>활성화 {date(contract.activatedAt)}</small>}</div><section className="drawer-section"><div className="panel-head"><div><h3>매출 인식 일정</h3><p>예정 매출과 실제 인식 상태</p></div><b>{schedule?.filter(x=>x.status==='RECOGNIZED').length||0}/{schedule?.length||0}</b></div>{schedule===null?<Spinner/>:schedule.length?<div className="revenue-schedule">{schedule.map(item=><div key={item.id}><span className="schedule-sequence">{item.sequenceNo}</span><span><b>{date(item.scheduledDate)}</b><small>{currencyMoney(item.amount,item.currencyCode)} · 기준 {money(item.baseAmount)}</small></span><Status value={item.status}/>{item.status!=='RECOGNIZED'&&<button className="btn btn-sm btn-secondary" onClick={()=>recognize(item)}>매출 인식</button>}</div>)}</div>:<Empty title="생성된 매출 일정이 없습니다" description="Draft 계약을 활성화하면 자동 생성됩니다."/>}</section><section className="drawer-section"><h3>갱신 계획</h3><div className="renewal-form"><label>진행 상태<select value={renewalStatus} onChange={e=>setRenewalStatus(e.target.value)}><option>NOT_STARTED</option><option>PLANNED</option><option>IN_PROGRESS</option><option>RENEWED</option><option>CHURNED</option></select></label><label>다음 행동<textarea rows={3} value={renewalAction} onChange={e=>setRenewalAction(e.target.value)} placeholder="갱신 의사결정에 필요한 다음 행동"/></label><button className="btn btn-secondary" onClick={saveRenewal}>갱신 계획 저장</button></div></section></div><div className="drawer-actions"><button className="btn btn-ghost" onClick={onClose}>닫기</button>{contract.status==='DRAFT'&&<button className="btn btn-primary" onClick={activate}>계약 활성화 · 일정 생성</button>}</div></aside></div>
}
function Approvals(props:Props){const [items,setItems]=useState<Approval[]>([]);const load=()=>api<{items:Approval[]}>('/api/v1/approvals').then(v=>setItems(v.items)).catch(e=>props.notify(errorMessage(e),true));useEffect(()=>{void load()},[]);async function decide(x:Approval,d:string){const comment=prompt(d==='APPROVE'?'승인 의견 (선택)':'반려 사유')||'';if(d==='REJECT'&&!comment)return;try{await api(`/api/v1/approvals/${x.id}/${d==='APPROVE'?'approve':'reject'}`,{method:'POST',body:JSON.stringify({comment,version:x.version})});props.notify(d==='APPROVE'?'승인했습니다.':'반려했습니다.');load()}catch(e){props.notify(errorMessage(e),true)}}return <Frame {...props} title="검토 · 승인" subtitle="관리자가 활성화한 정책 대상만 이 화면에 나타납니다."><div className="approval-note"><span>i</span><div><b>정책 기반 절차</b><p>승인 정책이 삭제되거나 모두 비활성화되면 메뉴와 버튼도 자동으로 사라집니다.</p></div></div><section className="panel table-panel">{items.length?<table><thead><tr><th>대상</th><th>정책</th><th>요청자</th><th>승인자</th><th>요청일</th><th>상태</th><th>작업</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.entityType}</b><small className="table-sub">{String(x.snapshot.name||x.snapshot.title||x.entityId)}</small></td><td>{x.policyName}</td><td>{x.requesterName}</td><td>{x.approverName||'미지정'}</td><td>{date(x.requestedAt)}</td><td><Status value={x.status}/></td><td>{x.status==='PENDING'&&x.approverId===props.user.id?<span className="inline-actions"><button onClick={()=>decide(x,'REJECT')}>반려</button><button className="approve" onClick={()=>decide(x,'APPROVE')}>승인</button></span>:'—'}</td></tr>)}</tbody></table>:<Empty icon="✓" title="검토할 요청이 없습니다" description="정책 조건에 맞는 업무에서 검토 요청을 보내면 이곳에 나타납니다."/>}</section></Frame>}

function DealIntelligence(props:Props){
  const [data,setData]=useState<any>(null)
  useEffect(()=>{api('/api/v1/deal-intelligence/coaching').then(setData).catch(e=>props.notify(errorMessage(e),true))},[])
  if(!data)return <Frame {...props} title="영업기회 분석"><Spinner/></Frame>
  const critical=data.attention.filter((x:any)=>x.riskLevel==='CRITICAL').length
  const pipeline=data.owners.reduce((sum:number,x:any)=>sum+x.pipeline,0)
  return <Frame {...props} title="영업기회 분석" subtitle="설명 가능한 위험 신호로 팀장이 오늘 점검할 영업건을 우선순위화합니다." actions={<span className="date-chip">위험 기준 {data.riskThreshold}점</span>}>
    <div className="kpi-grid"><KPI label="점검 대상 영업기회" value={`${data.attention.length}건`} foot="규칙 기반 위험 탐지" tone="violet" icon="◇"/><KPI label="긴급 점검 대상" value={`${critical}건`} foot="즉시 코칭이 필요합니다" tone="amber" icon="!"/><KPI label="팀 파이프라인" value={money(pipeline)} foot={`${data.owners.length}명 담당자`} tone="blue" icon="↗"/><KPI label="평균 건강도" value={`${(data.owners.reduce((s:number,x:any)=>s+x.averageHealth,0)/Math.max(1,data.owners.length)).toFixed(0)}`} foot="100점 기준" tone="teal" icon="✓"/></div>
    <div className="intelligence-stack"><section className="panel table-panel"><div className="panel-head"><div><h2>팀장 검토 대기</h2><p>위험 점수가 높은 순서입니다.</p></div></div>{data.attention.length?<table><thead><tr><th>영업기회</th><th>담당자</th><th>건강도</th><th>주요 위험</th><th>권장 행동</th></tr></thead><tbody>{data.attention.map((x:any)=><tr key={x.opportunityId}><td><b>{x.opportunityName}</b><small className="table-sub">{x.customerName}</small></td><td>{x.ownerName}</td><td><span className={`risk-score risk-${x.riskLevel.toLowerCase()}`}>{x.healthScore}<small>-{x.riskScore}</small></span></td><td>{x.factors.slice(0,2).map((f:any)=><span className="factor-chip" key={f.code}>{f.name}</span>)}</td><td>{x.recommendations[0]||'현재 권장 행동 없음'}</td></tr>)}</tbody></table>:<Empty icon="✓" title="위험 영업기회가 없습니다" description="현재 데이터 범위의 Open Deal이 설정된 위험 기준보다 양호합니다."/>}</section>
    <section className="panel table-panel"><div className="panel-head"><div><h2>영업 코칭</h2><p>담당자별 실행 공백</p></div></div><table><thead><tr><th>담당자</th><th>진행 중</th><th>위험</th><th>다음 행동 미정</th><th>단계 정체</th><th>평균 건강도</th></tr></thead><tbody>{data.owners.map((x:any)=><tr key={x.ownerId}><td><b>{x.ownerName}</b><small className="table-sub">{money(x.pipeline)}</small></td><td>{x.openDeals}</td><td><b className={x.atRiskDeals?'danger-text':''}>{x.atRiskDeals}</b></td><td>{x.noNextAction}</td><td>{x.stalledDeals}</td><td>{x.averageHealth.toFixed(0)}</td></tr>)}</tbody></table></section></div>
  </Frame>
}

const relationshipTypes=['REPORTS_TO','INFLUENCES','WORKS_WITH','BLOCKS','TRUSTS','ADVISES','OTHER']
const whiteSpaceStatuses=['NOT_OFFERED','DISCOVERY','OPPORTUNITY','CUSTOMER','NOT_APPLICABLE']
const lines=(value:string)=>value.split('\n').map(x=>x.trim()).filter(Boolean)

function CustomerDetailV12(props:Props&{id:string}){
  const [data,setData]=useState<any>(null),[graph,setGraph]=useState<any>(null),[plan,setPlan]=useState<any>(null),[approval,setApproval]=useState<any>(null)
  const [editing,setEditing]=useState(false)
  const [removing,setRemoving]=useState(false),[removeBusy,setRemoveBusy]=useState(false)
  const can=(permission:string)=>props.user.isBootstrap||(props.user.permissions||[]).some(x=>x==='admin:*'||x===permission)
  const contacts=useContacts(props.id,props.notify)
  const load=()=>Promise.all([api(`/api/v1/customers/${props.id}/360`),api(`/api/v1/customers/${props.id}/relationships`),api(`/api/v1/customers/${props.id}/account-plan`)]).then(([d,g,p])=>{setData(d);setGraph(g);setPlan(p)}).catch(e=>props.notify(errorMessage(e),true))
  useEffect(()=>{void load();if(props.approvalEnabled)api(`/api/v1/approvals/capability?entityType=CUSTOMER&entityId=${props.id}`).then(setApproval).catch(()=>{})},[props.id])
  async function addRelationship(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api(`/api/v1/customers/${props.id}/relationships`,{method:'POST',body:JSON.stringify({sourceContactId:f.get('source'),targetContactId:f.get('target'),relationshipType:f.get('type'),strength:Number(f.get('strength')),description:f.get('description'),active:true,version:0})});props.notify('담당자 관계를 연결했습니다.');e.currentTarget.reset();load()}catch(e){props.notify(errorMessage(e),true)}}
  async function removeRelationship(edge:any){if(!confirm('이 담당자 관계를 삭제할까요?'))return;try{await api(`/api/v1/customers/${props.id}/relationships/${edge.id}?version=${edge.version}`,{method:'DELETE'});props.notify('담당자 관계를 삭제했습니다.');load()}catch(e){props.notify(errorMessage(e),true)}}
  // Deleting a customer keeps its history: the API turns the request into a
  // deactivation when anything references the account, and says so.
  async function removeCustomer(){setRemoveBusy(true);try{const r=await api<{deleted?:boolean;note?:string}>(`/api/v1/customers/${props.id}`,{method:'DELETE'});props.notify(r.note||'고객을 삭제했습니다.');navigate('/app/customers')}catch(e){props.notify(errorMessage(e),true);setRemoveBusy(false);setRemoving(false)}}
  async function savePlan(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const saved=await api(`/api/v1/customers/${props.id}/account-plan`,{method:'PUT',body:JSON.stringify({planYear:Number(f.get('planYear')),status:f.get('status'),strategy:f.get('strategy'),customerGoals:lines(String(f.get('customerGoals')||'')),strategicInitiatives:lines(String(f.get('strategicInitiatives')||'')),ourObjectives:lines(String(f.get('ourObjectives')||'')),whiteSpaces:plan.whiteSpaces,competitors:lines(String(f.get('competitors')||'')),risks:lines(String(f.get('risks')||'')),targetRevenue:Number(f.get('targetRevenue')),potentialRevenue:Number(f.get('potentialRevenue')),version:plan.version})});setPlan(saved);props.notify('Account Plan을 저장했습니다.')}catch(e){props.notify(errorMessage(e),true)}}
  function addWhiteSpace(){setPlan((p:any)=>({...p,whiteSpaces:[...p.whiteSpaces,{id:'',productName:'',status:'NOT_OFFERED',potentialAmount:0,notes:''}]}))}
  function updateWhiteSpace(index:number,key:string,value:any){setPlan((p:any)=>({...p,whiteSpaces:p.whiteSpaces.map((x:any,i:number)=>i===index?{...x,[key]:value}:x)}))}
  function removeWhiteSpace(index:number){setPlan((p:any)=>({...p,whiteSpaces:p.whiteSpaces.filter((_:any,i:number)=>i!==index)}))}
  const editModal=editing?<CustomerModal customer={data?.customer} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);load()}} notify={props.notify}/>:null
  if(!data||!graph||!plan)return <Frame {...props} title="고객 360"><Spinner/></Frame>
  const c:Customer=data.customer
  return <Frame {...props} title={c.name} subtitle={`${c.industry||'산업 미지정'} · 담당 ${c.ownerName}`} actions={<><button className="btn btn-secondary" onClick={()=>setEditing(true)}>편집</button>{approval?.enabled&&approval.canRequest&&<button className="btn btn-primary" onClick={async()=>{try{await api('/api/v1/approvals',{method:'POST',body:JSON.stringify({entityType:'CUSTOMER',entityId:c.id})});props.notify('검토 요청을 보냈습니다.')}catch(e){props.notify(errorMessage(e),true)}}}>검토 요청</button>}{can('customer:delete')&&<button className="btn btn-danger" onClick={()=>setRemoving(true)}>고객 삭제</button>}</>}>
    <div className="customer-hero"><span className="customer-logo xl">{initials(c.name, 2)}</span><div><div className="hero-tags"><Status value={c.customerType}/>{c.grade&&<span className="grade">{c.grade}등급</span>}<Status value={c.health}/></div><p>{c.address||'주소 정보 없음'} · {c.phone||'전화 정보 없음'}</p></div><div className="customer-metrics"><Metric label="누적 매출" value={money(data.metrics.cumulativeRevenue)}/><Metric label="진행 파이프라인" value={money(data.metrics.openPipeline)}/><Metric label="관계 점수" value={`${graph.metrics.relationshipScore}/100`}/><Metric label="지지자" value={`${graph.metrics.champions}명`}/></div></div>
    <CustomerRiskBand customerId={props.id}/>
    <IntelligencePanel customerId={props.id} canWrite={can('intelligence:write')} canRun={can('intelligence:run')} notify={props.notify}/>
    <ContactsPanel customerId={props.id} canWrite={can('contact:write')} contacts={contacts} onChanged={load} notify={props.notify}/>
    <div className="relationship-grid"><section className="panel relationship-panel"><div className="panel-head"><div><h2>의사결정 관계도</h2><p>의사결정 구조와 영향 관계</p></div><span className="date-chip">담당자 {graph.metrics.contacts}명 · 평균 관계강도 {graph.metrics.averageStrength}</span></div><RelationshipGraphView graph={graph}/>{graph.edges.length>0&&<div className="relationship-edge-list">{graph.edges.map((x:any)=><div key={x.id}><span><b>{x.sourceName}</b> <Status value={x.relationshipType}/> <b>{x.targetName}</b></span><small>{x.description||`관계 강도 ${x.strength}`}</small><button className="danger" onClick={()=>removeRelationship(x)}>삭제</button></div>)}</div>}{graph.nodes.length<2?<div className="inline-hint">관계를 연결하려면 담당자가 2명 이상 필요합니다. 위 <b>고객 담당자</b>에서 먼저 등록하세요.</div>:<form className="relationship-form" onSubmit={addRelationship}><select name="source" required defaultValue=""><option value="">시작 담당자</option>{graph.nodes.map((x:any)=><option key={x.id} value={x.id}>{x.name}{x.title?` · ${x.title}`:''}</option>)}</select><select name="type">{relationshipTypes.map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select name="target" required defaultValue=""><option value="">대상 담당자</option>{graph.nodes.map((x:any)=><option key={x.id} value={x.id}>{x.name}{x.title?` · ${x.title}`:''}</option>)}</select><input name="strength" type="number" min="0" max="100" defaultValue="50" aria-label="관계 강도"/><input name="description" placeholder="관계 설명"/><button className="btn btn-secondary">관계 연결</button></form>}</section>
    <section className="panel relationship-metrics"><div className="panel-head"><div><h2>관계 분석</h2><p>고객 내부 지지 기반</p></div></div><div className="relationship-score"><strong>{graph.metrics.relationshipScore}</strong><span>/ 100</span></div><div className="info-list"><div><span>의사결정자</span><b>{graph.metrics.decisionMakers}명</b></div><div><span>지지자</span><b>{graph.metrics.champions}명</b></div><div><span>우호 / 반대</span><b>{graph.metrics.supporters} / {graph.metrics.opponents}</b></div><div><span>등록된 관계</span><b>{graph.edges.length}개</b></div></div></section></div>
    <form key={`${plan.id||'new'}-${plan.planYear}`} className="panel account-plan form" onSubmit={savePlan}><div className="panel-head"><div><h2>전략 고객 계획</h2><p>고객 목표, 공략 전략과 미판매 영역을 연간 단위로 관리합니다.</p></div><div className="account-plan-controls"><input name="planYear" type="number" min="2000" max="2200" value={plan.planYear} onChange={e=>setPlan({...plan,planYear:Number(e.target.value)})}/><select name="status" value={plan.status} onChange={e=>setPlan({...plan,status:e.target.value})}>{['DRAFT','ACTIVE','ARCHIVED'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><button className="btn btn-primary">계획 저장</button></div></div><div className="form-grid"><label className="span-2">고객 공략 전략<textarea name="strategy" rows={4} defaultValue={plan.strategy||''} placeholder="고객의 전략 과제와 우리가 만들 사업 가치를 기술합니다."/></label><label>고객 목표 · 줄바꿈 구분<textarea name="customerGoals" rows={4} defaultValue={(plan.customerGoals||[]).join('\n')}/></label><label>전략 과제 · 줄바꿈 구분<textarea name="strategicInitiatives" rows={4} defaultValue={(plan.strategicInitiatives||[]).join('\n')}/></label><label>우리의 목표 · 줄바꿈 구분<textarea name="ourObjectives" rows={4} defaultValue={(plan.ourObjectives||[]).join('\n')}/></label><label>경쟁사 · 줄바꿈 구분<textarea name="competitors" rows={4} defaultValue={(plan.competitors||[]).join('\n')}/></label><label>위험 요인 · 줄바꿈 구분<textarea name="risks" rows={4} defaultValue={(plan.risks||[]).join('\n')}/></label><label>연간 목표 매출<input name="targetRevenue" type="number" min="0" value={plan.targetRevenue} onChange={e=>setPlan({...plan,targetRevenue:Number(e.target.value)})}/></label><label>잠재 매출<input name="potentialRevenue" type="number" min="0" value={plan.potentialRevenue} onChange={e=>setPlan({...plan,potentialRevenue:Number(e.target.value)})}/></label></div><div className="white-space-head"><div><h3>미판매 영역 분석</h3><p>아직 제안하지 않은 상품과 교차판매 가능성을 찾아냅니다.</p></div><button type="button" className="btn btn-secondary btn-sm" onClick={addWhiteSpace}>＋ 상품 기회</button></div><div className="white-space-list">{plan.whiteSpaces.map((x:any,i:number)=><div className="white-space-row" key={x.id||i}><input value={x.productName} onChange={e=>updateWhiteSpace(i,'productName',e.target.value)} placeholder="상품 · 서비스" required/><select value={x.status} onChange={e=>updateWhiteSpace(i,'status',e.target.value)}>{whiteSpaceStatuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><input type="number" min="0" value={x.potentialAmount} onChange={e=>updateWhiteSpace(i,'potentialAmount',Number(e.target.value))} placeholder="잠재 금액"/><input value={x.notes||''} onChange={e=>updateWhiteSpace(i,'notes',e.target.value)} placeholder="발견 내용과 다음 행동"/><button type="button" className="danger" onClick={()=>removeWhiteSpace(i)}>×</button></div>)}{!plan.whiteSpaces.length&&<Empty title="미판매 영역이 없습니다" description="미제안 상품을 추가하면 Cross-sell MCP가 안전하게 탐색합니다."/>}</div></form>
    <div className="detail-grid"><section className="panel span-2"><div className="panel-head"><div><h2>영업기회</h2><p>현재 진행 중인 영업 흐름</p></div><button className="btn btn-sm btn-secondary" onClick={()=>navigate('/app/opportunities?new=1')}>＋ 생성</button></div>{data.opportunities.length?<div className="deal-list">{data.opportunities.map((o:Opportunity)=><div className="deal-row" key={o.id}><span className="stage-dot" style={{background:o.stageColor}}/><span className="deal-name"><b>{o.name}</b><small>{o.nextAction||'다음 행동 미정'}</small></span><b>{money(o.expectedAmount)}</b><span className="stage-pill" style={{'--stage':o.stageColor} as React.CSSProperties}>{o.stageName}</span></div>)}</div>:<Empty title="영업기회가 없습니다" description="이 고객의 첫 영업기회를 만들어보세요."/>}</section><section className="panel"><div className="panel-head"><div><h2>최근 활동</h2><p>고객 접점</p></div></div>{data.activities.length?<div className="timeline compact">{data.activities.slice(0,5).map((a:Activity)=><div className="timeline-item" key={a.id}><span className={`timeline-dot type-${a.activityType.toLowerCase()}`}>{activityIcon(a.activityType)}</span><div><b>{a.subject}</b><p>{a.ownerName} · {relative(a.occurredAt)}</p></div></div>)}</div>:<Empty title="활동이 없습니다" description="첫 고객 접점을 기록하세요."/>}</section></div>
    <VoicePanel customerId={props.id} canWrite={props.user.isBootstrap||(props.user.permissions||[]).some(x=>x==='admin:*'||x==='voice:write')} notify={props.notify}/>
    {editModal}
    {removing&&<Confirm title="고객 삭제" confirmLabel="고객 삭제" requireText={c.name} busy={removeBusy} onCancel={()=>setRemoving(false)} onConfirm={removeCustomer}
      description={<><p><b>{c.name}</b> 고객을 삭제합니다. 담당자, 활동, 작업, 전략 고객 계획이 함께 삭제됩니다.</p><p>영업기회·계약·견적·고객 요청·매출 이력이 하나라도 있으면 기록 보존을 위해 삭제 대신 <b>비활성</b>으로 전환되며 목록에서 숨겨집니다.</p><p>확인을 위해 고객명을 입력하세요.</p></>}/>}
  </Frame>
}

function RelationshipGraphView({graph}:{graph:any}){
  const nodes=(graph.nodes as any[]).slice(0,15),width=1120,rowHeight=145,rows=Math.max(1,Math.ceil(nodes.length/3)),height=rows*rowHeight+34
  const positions=Object.fromEntries(nodes.map((x:any,i:number)=>[x.id,{x:172+(i%3)*362,y:82+Math.floor(i/3)*rowHeight}]))
  if(!nodes.length)return <Empty title="담당자가 없습니다" description="담당자를 등록하고 의사결정자와 지지자를 지정하세요."/>
  return <div className="relationship-canvas"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="고객 담당자 관계도"><defs><marker id="relationship-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z"/></marker></defs>{graph.edges.map((e:any)=>{const a=positions[e.sourceContactId],b=positions[e.targetContactId];return a&&b?<g key={e.id}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} markerEnd="url(#relationship-arrow)"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-9}>{label(e.relationshipType)}</text></g>:null})}{nodes.map((n:any)=>{const p=positions[n.id];return <g className={`relationship-node sentiment-${n.sentiment.toLowerCase()}`} key={n.id} transform={`translate(${p.x-116},${p.y-41})`}><rect width="232" height="82" rx="14"/><circle cx="28" cy="28" r="16"/><text className="node-initial" x="28" y="33" textAnchor="middle">{initials(n.name, 1)}</text><text className="node-name" x="54" y="25">{n.name}</text><text className="node-role" x="54" y="44">{contactRoleLabel(n.relationshipRole)} · 영향력 {label(n.influence)}</text><text className="node-strength" x="54" y="61">관계 {n.relationshipStrength} · 결정력 {n.decisionPower}</text></g>})}</svg></div>
}

function OpportunityDrawerV11({opportunity:o,onClose,onUpdated,approvalEnabled,notify,canIntelligenceWrite}:{opportunity:Opportunity;onClose:()=>void;onUpdated:()=>void;approvalEnabled:boolean;notify:Props['notify'];canIntelligenceWrite:boolean}){
  const [cap,setCap]=useState<any>(null),[health,setHealth]=useState<any>(null),[inspection,setInspection]=useState<any>(null),[playbook,setPlaybook]=useState<any>(null),[team,setTeam]=useState<any[]>([]),[collaborators,setCollaborators]=useState<any[]>([]),[memberId,setMemberId]=useState(''),[memberRole,setMemberRole]=useState('PRESALES'),[responsibility,setResponsibility]=useState('')
  const surface=useDialog(onClose)
  const [editing,setEditing]=useState(false)
  const load=()=>Promise.all([api(`/api/v1/opportunities/${o.id}/health`),api(`/api/v1/opportunities/${o.id}/inspection?days=7`),api(`/api/v1/opportunities/${o.id}/playbook`),api<{items:any[]}>(`/api/v1/opportunities/${o.id}/team`),api<{items:any[]}>('/api/v1/collaborators?limit=200')]).then(([h,i,p,t,c])=>{setHealth(h);setInspection(i);setPlaybook(p);setTeam(t.items);setCollaborators(c.items)}).catch(e=>notify(errorMessage(e),true))
  useEffect(()=>{void load();if(approvalEnabled)api(`/api/v1/approvals/capability?entityType=OPPORTUNITY&entityId=${o.id}`).then(setCap).catch(()=>{})},[o.id])
  async function toggle(item:any){try{const v=await api(`/api/v1/opportunities/${o.id}/playbook/${item.id}`,{method:'PUT',body:JSON.stringify({completed:!item.completed,notes:item.notes||''})});setPlaybook(v);notify('Playbook 진행상태를 저장했습니다.')}catch(e){notify(errorMessage(e),true)}}
  async function addMember(){if(!memberId)return;try{await api(`/api/v1/opportunities/${o.id}/team/${memberId}`,{method:'PUT',body:JSON.stringify({role:memberRole,responsibility,version:0})});notify('영업기회 협업팀 구성원을 추가했습니다.');setMemberId('');setResponsibility('');load()}catch(e){notify(errorMessage(e),true)}}
  async function removeMember(item:any){if(!confirm(`${item.displayName} 구성원을 제외할까요?`))return;try{await api(`/api/v1/opportunities/${o.id}/team/${item.userId}?version=${item.version}`,{method:'DELETE'});notify('영업기회 협업팀 구성원을 제외했습니다.');load()}catch(e){notify(errorMessage(e),true)}}
  return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside ref={surface} className="drawer drawer-wide" role="dialog" aria-modal="true"><div className="drawer-head"><div><p className="eyebrow">영업기회 점검</p><h2>{o.name}</h2><p>{o.customerName} · {o.ownerName}</p></div><button className="icon-btn" onClick={onClose}>×</button></div><div className="drawer-body">
    <div className="amount-hero"><small>Expected Amount · {o.currencyCode||'KRW'}</small><strong>{currencyMoney(o.expectedAmount,o.currencyCode||'KRW')}</strong><span>{o.stageName} · 기준 {money(baseOpportunityAmount(o))} · 가중 {money(baseOpportunityWeighted(o))}</span></div>
    {health?<section className={`deal-health-card level-${health.riskLevel.toLowerCase()}`}><div className="health-gauge"><strong>{health.healthScore}</strong><small>건강도</small></div><div><div className="panel-head"><h3>{health.riskLevel} · Risk +{health.riskScore}</h3><Status value={health.riskLevel}/></div>{health.factors.map((f:any)=><div className="health-factor" key={f.code}><b>+{f.riskScore} {f.name}</b><span>{f.description}</span><small>→ {f.recommendedAction}</small></div>)}</div></section>:<Spinner/>}
    <div className="drawer-section"><IntelligencePanel customerId={o.customerId} opportunityId={o.id} canWrite={canIntelligenceWrite} notify={notify} compact/></div>
    <section className="drawer-section"><div className="panel-head"><div><h3>{playbook?.name||`${o.stageName} Playbook`}</h3><p>{playbook?.guidance||'관리자가 Stage별 Playbook을 설정할 수 있습니다.'}</p></div>{playbook?.items?.length>0&&<b>{playbook.completed}/{playbook.items.length}</b>}</div>{playbook?.items?.length?playbook.items.map((item:any)=><label className={`playbook-check ${item.completed?'done':''}`} key={item.id}><input type="checkbox" checked={item.completed} onChange={()=>toggle(item)}/><span><b>{item.title}{item.required&&<em>필수</em>}</b><small>{item.description||item.itemType}</small></span></label>):<Empty title="현재 단계 실행 지침이 없습니다" description="관리자 영업 실행 정책에서 체크리스트와 안내를 설정하세요."/>}</section>
    <section className="drawer-section"><div className="panel-head"><div><h3>최근 7일 변화</h3><p>영업기회 점검</p></div><b>{inspection?.changeCount||0} changes</b></div>{inspection?.changes?.length?inspection.changes.slice(0,8).map((x:any,i:number)=><div className="change-row" key={`${x.field}-${i}`}><b>{x.field}</b><span>{String(x.before??'—')}</span><em>→</em><span>{String(x.after??'—')}</span><small>{date(x.changedAt)}</small></div>):<p className="muted-copy">최근 변경이 없습니다.</p>}</section>
    <section className="drawer-section opportunity-team"><div className="panel-head"><div><h3>영업기회 협업팀</h3><p>기술영업, 팀장, 법무 등 협업 역할</p></div><b>{team.length} members</b></div>{team.map(x=><div className="team-member" key={x.userId}><span className="avatar">{initials(x.displayName, 1)}</span><div><b>{x.displayName}</b><small>{x.title||x.username} · {x.responsibility||'책임 미지정'}</small></div><Status value={x.role}/><button className="danger" onClick={()=>removeMember(x)}>제외</button></div>)}{!team.length&&<p className="muted-copy">담당자 외 협업 구성원이 없습니다.</p>}<div className="team-add"><select value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">협업 사용자 선택</option>{collaborators.filter(x=>x.id!==o.ownerId&&!team.some(t=>t.userId===x.id)).map(x=><option key={x.id} value={x.id}>{x.displayName} · {x.organizationName||x.title||x.username}</option>)}</select><select value={memberRole} onChange={e=>setMemberRole(e.target.value)}>{['PRESALES','CONSULTANT','MANAGER','EXECUTIVE_SPONSOR','LEGAL','DELIVERY','OTHER'].map(x=><option key={x}>{x}</option>)}</select><input value={responsibility} onChange={e=>setResponsibility(e.target.value)} placeholder="담당 책임"/><button className="btn btn-secondary btn-sm" onClick={addMember} disabled={!memberId}>추가</button></div><div className="scope-note">영업기회 협업팀은 협업 정보를 제공하며 사용자의 데이터 범위를 확대하지 않습니다.</div></section>
  </div><div className="drawer-actions"><button className="btn btn-secondary" onClick={load}>다시 분석</button><button className="btn btn-secondary" onClick={()=>setEditing(true)}>편집</button>{cap?.enabled&&cap.canRequest&&<button className="btn btn-primary" onClick={async()=>{try{await api('/api/v1/approvals',{method:'POST',body:JSON.stringify({entityType:'OPPORTUNITY',entityId:o.id})});notify('팀장 검토를 요청했습니다.');onUpdated()}catch(e){notify(errorMessage(e),true)}}}>검토 요청</button>}</div>{editing&&<OpportunityEditModal opportunity={o} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);notify('Opportunity를 저장했습니다.');onUpdated()}} notify={notify}/>}</aside></div>
}

function OpportunityEditModal({opportunity:o,onClose,onSaved,notify}:{opportunity:Opportunity;onClose:()=>void;onSaved:()=>void;notify:Props['notify']}){
  const [busy,setBusy]=useState(false)
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true)
    const probability=String(f.get('probability')||'')
    const body={name:f.get('name'),expectedAmount:Number(f.get('amount')),currencyCode:o.currencyCode||'KRW',probability:probability?Number(probability):null,expectedCloseDate:f.get('closeDate')||null,forecastCategory:f.get('forecast'),competitor:f.get('competitor'),nextAction:f.get('nextAction'),nextActionDate:f.get('nextActionDate')||null,customFields:{},version:o.version}
    try{await api(`/api/v1/opportunities/${o.id}`,{method:'PUT',body:JSON.stringify(body)});onSaved()}catch(err){notify(errorMessage(err),true)}finally{setBusy(false)}}
  return <Modal title={`${o.name} 편집`} onClose={onClose} wide><form className="form" onSubmit={submit}><div className="form-grid">
    <label className="span-2">영업기회 이름 *<input name="name" required autoFocus defaultValue={o.name}/></label>
    <label>예상 금액 ({o.currencyCode||'KRW'})<input name="amount" type="number" min="0" step="0.01" defaultValue={o.expectedAmount}/><small>거래통화와 고정 환율은 생성 시점 값을 유지합니다.</small></label>
    <label>성공확률 (%)<input name="probability" type="number" min="0" max="100" defaultValue={o.probability}/><small>비우면 단계 기본 확률을 사용합니다.</small></label>
    <label>전망 분류<select name="forecast" defaultValue={o.forecastCategory}>{['PIPELINE','BEST_CASE','COMMIT','CLOSED','OMITTED'].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>예상 계약일<input name="closeDate" type="date" defaultValue={o.expectedCloseDate?.slice(0,10)||''}/></label>
    <label>경쟁사<input name="competitor" defaultValue={o.competitor||''}/></label>
    <label>다음 행동<input name="nextAction" defaultValue={o.nextAction||''} placeholder="예: 기술 검토 미팅 확정"/></label>
    <label>다음 행동일<input name="nextActionDate" type="date" defaultValue={o.nextActionDate?.slice(0,10)||''}/></label>
  </div><div className="alert"><b>단계 변경은 파이프라인 보드에서</b><span>Stage를 바꾸면 Exit Criteria 검사가 실행되므로 Pipeline 화면의 Drag &amp; Drop 또는 Stage 변경 기능을 사용하세요.</span></div>
    <div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={onClose}>취소</button><button className="btn btn-primary" disabled={busy}>{busy?'저장 중…':'변경 저장'}</button></div></form></Modal>
}

function ForecastV11(props:Props){
  const [data,setData]=useState<any>(null),[kpi,setKpi]=useState<any>(null),[intel,setIntel]=useState<any>(null)
  useEffect(()=>{Promise.all([api('/api/v1/forecasts'),api('/api/v1/sales/kpi'),api('/api/v1/forecasts/intelligence?days=7')]).then(([f,k,i])=>{setData(f);setKpi(k);setIntel(i)}).catch(e=>props.notify(errorMessage(e),true))},[])
  if(!data||!intel)return <Frame {...props} title="매출 전망 분석"><Spinner/></Frame>
  const grouped=Object.values((intel.movements as any[]).reduce((a:any,x:any)=>{const row=a[x.type]||(a[x.type]={type:x.type,count:0,amount:0});row.count++;row.amount+=x.amount;return a},{})) as any[]
  return <Frame {...props} title="매출 전망 분석" subtitle="거래통화를 KRW 기준으로 환산해 Snapshot 변화와 Manager 판단을 일관되게 비교합니다." actions={<span className="date-chip">{intel.fromDate} → {intel.toDate}</span>}>
    <div className="kpi-grid"><KPI label="담당자 확약" value={money(intel.repCommit)} foot="Sales Rep Forecast" tone="blue" icon="↗"/><KPI label="팀장 확약" value={money(intel.managerCommit)} foot="Override 반영" tone="violet" icon="◆"/><KPI label="가중 전망" value={money(intel.weighted)} foot="System Forecast" tone="teal" icon="✓"/><KPI label="주간 변화" value={money(intel.changeAmount)} foot={`${intel.changeAmount>=0?'+':''}${((intel.changeAmount/Math.max(1,intel.previousAmount))*100).toFixed(1)}%`} tone="amber" icon="◎"/></div>
    <div className="forecast-intel-grid"><section className="panel waterfall"><div className="panel-head"><div><h2>전망 변화 분석</h2><p>파이프라인 변화 원인</p></div></div><div className="waterfall-total"><span>지난 시점 <b>{money(intel.previousAmount)}</b></span><em>→</em><span>현재 시점 <b>{money(intel.currentAmount)}</b></span></div>{grouped.length?grouped.map(x=><div className="movement-row" key={x.type}><Status value={x.type}/><span>{x.count}건</span><b className={x.amount<0?'negative':'positive'}>{x.amount>0?'+':''}{money(x.amount)}</b></div>):<Empty title="전망 변화가 없습니다" description="일별 Snapshot이 누적되면 신규, Lost, Slippage와 금액 증감을 설명합니다."/>}</section>
    <section className="panel forecast-board"><div className="panel-head"><div><h2>전망 분류</h2><p>기준통화 {data.baseCurrency||'KRW'}</p></div><span className="date-chip">Generated {new Date(data.generatedAt).toLocaleTimeString('ko-KR')}</span></div><div className="forecast-bars">{data.categories.map((c:any)=>{const width=data.pipeline?Math.max(4,c.amount/data.pipeline*100):0;return <div key={c.category}><header><Status value={c.category}/><b>{money(c.amount)}</b><small>{c.count}건 · 가중 {money(c.weightedAmount)}</small></header><div><span style={{width:`${width}%`}}/></div></div>})}</div>{data.currencies?.length>0&&<div className="currency-mix"><small>거래통화 구성</small>{data.currencies.map((c:any)=><span key={c.currencyCode}><b>{c.currencyCode}</b>{currencyMoney(c.nativeAmount,c.currencyCode)}<em>→ {money(c.baseAmount)}</em></span>)}</div>}<div className="forecast-foot"><span>이번 달 매출 <b>{money(kpi?.revenueThisMonth)}</b></span><span>목표 달성률 <b>{(kpi?.attainmentPercent||0).toFixed(1)}%</b></span></div></section></div>
  </Frame>
}


function healthLabel(v:string){return ({NO_RECENT_ACTIVITY:'최근 30일간 활동 없음',CLOSE_DATE_OVERDUE:'예상 계약일 경과',NO_NEXT_ACTION:'다음 행동 미지정',STAGE_STALLED:'Stage 장기 정체'} as Record<string,string>)[v]||v}
